version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: harucare-mongodb
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB:-harucare}
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: mongod --auth
    restart: unless-stopped
    networks:
      - harucare-network

networks:
  harucare-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local