version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: harucare-mongodb
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB:-harucare}
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: mongod --auth
    restart: unless-stopped
    networks:
      - harucare-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: harucare-app
    ports:
      - "3000:3000"
    environment:
      # 환경 변수는 .env 파일에서 로드됩니다.
      # Docker Compose가 .env 파일을 자동으로 로드합니다.
      # 필요한 경우 여기에 명시적으로 추가하거나, .env 파일에 정의하세요.
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DB}?authSource=admin
      - FITBIT_CLIENT_ID=${FITBIT_CLIENT_ID}
      - FITBIT_CLIENT_SECRET=${FITBIT_CLIENT_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL}
    depends_on:
      - mongodb
    networks:
      - harucare-network
    restart: unless-stopped

networks:
  harucare-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
